RESOURCE_MAGIC = b"\x40\x2c"

FONT_START_CHAR = 30
FONT_GLYPH_COUNT = 226
FONT_GLYPH_HEIGHTS = [24, 12, 17, 24, 112]
FONT_EXPORT_ATLAS_WIDTH = 256
FONT_EXPORT_ATLAS_HEIGHT = 256

EXPORT_FONT_FOLDER = "fonts"
EXPORT_LOCALE_EXTENSION = "po"
EXPORT_LOCALE_FOLDER = "locale"
EXPORT_LOCALE_SCRIPTS_FOLDER = "scripts"
EXPORT_PALETTE_EXTENSION = "xml"
EXPORT_PALETTE_FOLDER = ""
EXPORT_SPRITE_EXTENSION = "png"
EXPORT_SPRITE_FOLDER = "sprites"
EXPORT_UNKNOWN_EXTENSION = "bin"
EXPORT_UNKNOWN_FOLDER = "raw"
